//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendoSyncStatus
    {
        public int Id { get; set; }
        public long LastId { get; set; }
        public System.DateTime LastSyncTime { get; set; }
    }
}
