//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceEvents
    {
        public int Id { get; set; }
        public System.DateTime DateTimeUtc { get; set; }
        public long CardNumber { get; set; }
        public int DeviceId { get; set; }
        public string DeviceCode { get; set; }
        public string DeviceDescription { get; set; }
        public string RegistrationType { get; set; }
        public System.DateTime CreatedAtUtc { get; set; }
        public Nullable<int> Hr_korisnik_id { get; set; }
        public string Source { get; set; }
    }
}
