//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DODATNO_OBRAZOVANJE
    {
        public int ID { get; set; }
        public int HR_KORISNIK_ID { get; set; }
        public int VRSTA_DODATNOG_OBRAZOVANJA_ID { get; set; }
        public Nullable<int> DOKUMENT_ID { get; set; }
        public string NAZIV { get; set; }
        public Nullable<System.DateTime> DATUM_STICANJA { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
        public Nullable<System.DateTime> DATUM_BRISANJA { get; set; }
        public string OBRISAN { get; set; }
        public Nullable<System.DateTime> DATUM_ISTEKA { get; set; }
        public string AKTIVNO { get; set; }
    
        public virtual DOKUMENT DOKUMENT { get; set; }
        public virtual HR_KORISNIK HR_KORISNIK { get; set; }
        public virtual VRSTA_DODATNOG_OBRAZOVANJA VRSTA_DODATNOG_OBRAZOVANJA { get; set; }
    }
}
