//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DODATNA_PRAVA_IZ_RADNOG_ODNOSA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DODATNA_PRAVA_IZ_RADNOG_ODNOSA()
        {
            this.HR_KORISNIK_DODATNA_PRAVA = new HashSet<HR_KORISNIK_DODATNA_PRAVA>();
        }
    
        public int ID { get; set; }
        public string NAZIV { get; set; }
        public string AKTIVNO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_KORISNIK_DODATNA_PRAVA> HR_KORISNIK_DODATNA_PRAVA { get; set; }
    }
}
