//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DODATNI_POTPISNIK
    {
        public int ID { get; set; }
        public int HR_KORISNIK_ID { get; set; }
        public int ORGANIZACIONA_JEDINICA_ID { get; set; }
    
        public virtual HR_KORISNIK HR_KORISNIK { get; set; }
        public virtual ORGANIZACIONA_JEDINICA ORGANIZACIONA_JEDINICA { get; set; }
    }
}
