//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOKUMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOKUMENT()
        {
            this.DODATNO_OBRAZOVANJE = new HashSet<DODATNO_OBRAZOVANJE>();
            this.HR_KORISNIK_DODATNA_PRAVA = new HashSet<HR_KORISNIK_DODATNA_PRAVA>();
            this.HR_KORISNIK = new HashSet<HR_KORISNIK>();
            this.LICNI_DOKUMENTI = new HashSet<LICNI_DOKUMENTI>();
            this.UGOVOR_O_RADU = new HashSet<UGOVOR_O_RADU>();
        }
    
        public int ID { get; set; }
        public System.Guid STREAM_ID { get; set; }
        public string NAZIV { get; set; }
        public string EKSTENZIJA { get; set; }
        public string PUTANJA { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DODATNO_OBRAZOVANJE> DODATNO_OBRAZOVANJE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_KORISNIK_DODATNA_PRAVA> HR_KORISNIK_DODATNA_PRAVA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_KORISNIK> HR_KORISNIK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICNI_DOKUMENTI> LICNI_DOKUMENTI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UGOVOR_O_RADU> UGOVOR_O_RADU { get; set; }
    }
}
