//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRZAVA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DRZAVA()
        {
            this.DRZAVLJANSTVO = new HashSet<DRZAVLJANSTVO>();
            this.OPSTINA = new HashSet<OPSTINA>();
            this.RAD_U_INOSTRANSTVU = new HashSet<RAD_U_INOSTRANSTVU>();
        }
    
        public int ID { get; set; }
        public string NAZIV { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
        public string KOD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRZAVLJANSTVO> DRZAVLJANSTVO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPSTINA> OPSTINA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RAD_U_INOSTRANSTVU> RAD_U_INOSTRANSTVU { get; set; }
    }
}
