//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRZAVNI_PRAZNICI
    {
        public int ID { get; set; }
        public string NAZIV { get; set; }
        public int MJESEC { get; set; }
        public int BROJ_DANA_PRAZNIKA { get; set; }
        public int UKUPAN_BROJ_SATI { get; set; }
    }
}
