//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_GRUPA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_GRUPA()
        {
            this.HR_KORISNIK_HR_GRUPA = new HashSet<HR_KORISNIK_HR_GRUPA>();
            this.PRAVA_PRISTUPA = new HashSet<PRAVA_PRISTUPA>();
        }
    
        public int ID { get; set; }
        public string NAZIV { get; set; }
        public string AKTIVNO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_KORISNIK_HR_GRUPA> HR_KORISNIK_HR_GRUPA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRAVA_PRISTUPA> PRAVA_PRISTUPA { get; set; }
    }
}
