//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_KORISNIK_PRERASPODJELA_SATI
    {
        public int ID { get; set; }
        public int HR_KORISNIK_ID { get; set; }
        public int RADNIK_ID { get; set; }
        public int GODINA { get; set; }
        public int MJESEC { get; set; }
        public Nullable<decimal> SATI_PRERASPODJELE { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
        public string OBRISANO { get; set; }
        public Nullable<System.DateTime> DATUM_BRISANJA { get; set; }
    
        public virtual HR_KORISNIK HR_KORISNIK { get; set; }
        public virtual HR_KORISNIK HR_KORISNIK1 { get; set; }
    }
}
