//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_KORISNIK_PRISUSTVO_PRAVA_PRISTUPA
    {
        public int ID { get; set; }
        public int HR_KORISNIK_ID { get; set; }
        public Nullable<int> RADNIK_ID { get; set; }
        public Nullable<int> ORGANIZACIONA_JEDINICA_ID { get; set; }
        public string OMOGUCI_EVIDENCIJU_SEBI { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
        public Nullable<System.DateTime> DATUM_IZMJENE { get; set; }
        public string AKTIVNO { get; set; }
        public string ZAKLJUCAVANJE_OJ { get; set; }
    
        public virtual HR_KORISNIK HR_KORISNIK { get; set; }
        public virtual HR_KORISNIK HR_KORISNIK1 { get; set; }
        public virtual ORGANIZACIONA_JEDINICA ORGANIZACIONA_JEDINICA { get; set; }
    }
}
