//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_KORISNIK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_KORISNIK()
        {
            this.DANI_GODISNJEG_ODMORA = new HashSet<DANI_GODISNJEG_ODMORA>();
            this.DODATNI_POTPISNIK = new HashSet<DODATNI_POTPISNIK>();
            this.DODATNO_OBRAZOVANJE = new HashSet<DODATNO_OBRAZOVANJE>();
            this.DRZAVLJANSTVO = new HashSet<DRZAVLJANSTVO>();
            this.EXPORT_PRISUSTVO_POINT = new HashSet<EXPORT_PRISUSTVO_POINT>();
            this.HR_KORISNIK_DODATNA_PRAVA = new HashSet<HR_KORISNIK_DODATNA_PRAVA>();
            this.HR_KORISNIK_FILTER = new HashSet<HR_KORISNIK_FILTER>();
            this.HR_KORISNIK_FILTER_UPOSLENIK = new HashSet<HR_KORISNIK_FILTER_UPOSLENIK>();
            this.HR_KORISNIK_HR_GRUPA = new HashSet<HR_KORISNIK_HR_GRUPA>();
            this.HR_KORISNIK_LOKACIJE_MAS = new HashSet<HR_KORISNIK_LOKACIJE_MAS>();
            this.HR_KORISNIK_PRERASPODJELA_SATI = new HashSet<HR_KORISNIK_PRERASPODJELA_SATI>();
            this.HR_KORISNIK_PRERASPODJELA_SATI1 = new HashSet<HR_KORISNIK_PRERASPODJELA_SATI>();
            this.HR_KORISNIK_PRISUSTVO = new HashSet<HR_KORISNIK_PRISUSTVO>();
            this.HR_KORISNIK_PRISUSTVO1 = new HashSet<HR_KORISNIK_PRISUSTVO>();
            this.HR_KORISNIK_PRISUSTVO_PRAVA_PRISTUPA = new HashSet<HR_KORISNIK_PRISUSTVO_PRAVA_PRISTUPA>();
            this.HR_KORISNIK_PRISUSTVO_PRAVA_PRISTUPA1 = new HashSet<HR_KORISNIK_PRISUSTVO_PRAVA_PRISTUPA>();
            this.HR_KORISNIK_RADNO_MJESTO = new HashSet<HR_KORISNIK_RADNO_MJESTO>();
            this.HR_LOG = new HashSet<HR_LOG>();
            this.KANDIDAT = new HashSet<KANDIDAT>();
            this.KONFIGURACIJA_VRSTA_PRISUSTVA = new HashSet<KONFIGURACIJA_VRSTA_PRISUSTVA>();
            this.KONFIGURACIJA = new HashSet<KONFIGURACIJA>();
            this.KONFIGURACIJA1 = new HashSet<KONFIGURACIJA>();
            this.LICNI_DOKUMENTI = new HashSet<LICNI_DOKUMENTI>();
            this.MIROVANJE_RADNOG_ODNOSA = new HashSet<MIROVANJE_RADNOG_ODNOSA>();
            this.ORGANIZACIONA_JEDINICA = new HashSet<ORGANIZACIONA_JEDINICA>();
            this.PRAVO_GODISNJI_ODMOR = new HashSet<PRAVO_GODISNJI_ODMOR>();
            this.PREBIVALISTE_BORAVISTE = new HashSet<PREBIVALISTE_BORAVISTE>();
            this.PRESTANAK_RADNOG_ODNOSA = new HashSet<PRESTANAK_RADNOG_ODNOSA>();
            this.RAD_U_INOSTRANSTVU = new HashSet<RAD_U_INOSTRANSTVU>();
            this.RADNI_STAZ = new HashSet<RADNI_STAZ>();
            this.RADNO_ISKUSTVO = new HashSet<RADNO_ISKUSTVO>();
            this.TEST = new HashSet<TEST>();
            this.ZAKLJUCAVANJE_EVIDENCIJE = new HashSet<ZAKLJUCAVANJE_EVIDENCIJE>();
        }
    
        public int ID { get; set; }
        public string IME { get; set; }
        public string PREZIME { get; set; }
        public string IME_RODITELJA { get; set; }
        public string DJEVOJACKO_PREZIME { get; set; }
        public string LOZINKA { get; set; }
        public string JMB { get; set; }
        public int SPOL_ID { get; set; }
        public Nullable<int> SLIKA_ID { get; set; }
        public Nullable<int> BRACNI_STATUS_ID { get; set; }
        public Nullable<System.DateTime> DATUM_RODJENJA { get; set; }
        public string MJESTO_RODJENJA { get; set; }
        public Nullable<int> OPSTINA_ID { get; set; }
        public Nullable<int> NARODNOST_ID { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
        public string DOZVOLA_ZA_BORAVAK_RAD { get; set; }
        public Nullable<System.DateTime> DATUM_IZMJENE { get; set; }
        public Nullable<int> SKOLSKA_SPREMA_ID { get; set; }
        public string STECENO_ZVANJE { get; set; }
        public string OBRAZOVNA_INSTITUCIJA { get; set; }
        public string BROJ_MOBILNOG_TELEFONA { get; set; }
        public string BROJ_FIXNOG_TELEFONA { get; set; }
        public string BROJ_LOKALA { get; set; }
        public string KATEGORIJA_VOZACKE_DOZVOLE { get; set; }
        public Nullable<System.DateTime> DATUM_POCETKA_RADA { get; set; }
        public Nullable<System.DateTime> DATUM_BRISANJA { get; set; }
        public string ACTIVE_DIRECTORY_KORISNIK { get; set; }
        public string OBRISAN { get; set; }
        public string AKTIVNO { get; set; }
        public string RACUNOVODSTVENI_BROJ { get; set; }
        public string DOMAIN_LOGON { get; set; }
        public string KOREKCIJA { get; set; }
        public string DJEVOJACKO_PREZIME_MAJKE { get; set; }
        public string IME_MAJKE { get; set; }
        public string EMAIL { get; set; }
        public string PACS_ID { get; set; }
        public string ADMIINISTRATIVNO { get; set; }
    
        public virtual BRACNI_STATUS BRACNI_STATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANI_GODISNJEG_ODMORA> DANI_GODISNJEG_ODMORA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DODATNI_POTPISNIK> DODATNI_POTPISNIK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DODATNO_OBRAZOVANJE> DODATNO_OBRAZOVANJE { get; set; }
        public virtual DOKUMENT DOKUMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRZAVLJANSTVO> DRZAVLJANSTVO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXPORT_PRISUSTVO_POINT> EXPORT_PRISUSTVO_POINT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_KORISNIK_DODATNA_PRAVA> HR_KORISNIK_DODATNA_PRAVA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_KORISNIK_FILTER> HR_KORISNIK_FILTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_KORISNIK_FILTER_UPOSLENIK> HR_KORISNIK_FILTER_UPOSLENIK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_KORISNIK_HR_GRUPA> HR_KORISNIK_HR_GRUPA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_KORISNIK_LOKACIJE_MAS> HR_KORISNIK_LOKACIJE_MAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_KORISNIK_PRERASPODJELA_SATI> HR_KORISNIK_PRERASPODJELA_SATI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_KORISNIK_PRERASPODJELA_SATI> HR_KORISNIK_PRERASPODJELA_SATI1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_KORISNIK_PRISUSTVO> HR_KORISNIK_PRISUSTVO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_KORISNIK_PRISUSTVO> HR_KORISNIK_PRISUSTVO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_KORISNIK_PRISUSTVO_PRAVA_PRISTUPA> HR_KORISNIK_PRISUSTVO_PRAVA_PRISTUPA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_KORISNIK_PRISUSTVO_PRAVA_PRISTUPA> HR_KORISNIK_PRISUSTVO_PRAVA_PRISTUPA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_KORISNIK_RADNO_MJESTO> HR_KORISNIK_RADNO_MJESTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_LOG> HR_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KANDIDAT> KANDIDAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KONFIGURACIJA_VRSTA_PRISUSTVA> KONFIGURACIJA_VRSTA_PRISUSTVA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KONFIGURACIJA> KONFIGURACIJA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KONFIGURACIJA> KONFIGURACIJA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICNI_DOKUMENTI> LICNI_DOKUMENTI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MIROVANJE_RADNOG_ODNOSA> MIROVANJE_RADNOG_ODNOSA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORGANIZACIONA_JEDINICA> ORGANIZACIONA_JEDINICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRAVO_GODISNJI_ODMOR> PRAVO_GODISNJI_ODMOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PREBIVALISTE_BORAVISTE> PREBIVALISTE_BORAVISTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESTANAK_RADNOG_ODNOSA> PRESTANAK_RADNOG_ODNOSA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RAD_U_INOSTRANSTVU> RAD_U_INOSTRANSTVU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RADNI_STAZ> RADNI_STAZ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RADNO_ISKUSTVO> RADNO_ISKUSTVO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEST> TEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZAKLJUCAVANJE_EVIDENCIJE> ZAKLJUCAVANJE_EVIDENCIJE { get; set; }
        public virtual NARODNOST NARODNOST { get; set; }
        public virtual OPSTINA OPSTINA { get; set; }
        public virtual SKOLSKA_SPREMA SKOLSKA_SPREMA { get; set; }
        public virtual SPOL SPOL { get; set; }
    }
}
