//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_KORISNIK_DODATNA_PRAVA
    {
        public int ID { get; set; }
        public int HR_KORISNIK_ID { get; set; }
        public int DODATNA_PRAVA_IZ_RADNOG_ODNOSA_ID { get; set; }
        public Nullable<int> DOKUMENT_ID { get; set; }
        public Nullable<System.DateTime> DATUM_POCETKA_PRAVA { get; set; }
        public Nullable<System.DateTime> DATUM_ZAVRSETKA_PRAVA { get; set; }
        public string NAPOMENA { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
        public Nullable<System.DateTime> DATUM_IZMJENE { get; set; }
        public string AKTIVNO { get; set; }
    
        public virtual DODATNA_PRAVA_IZ_RADNOG_ODNOSA DODATNA_PRAVA_IZ_RADNOG_ODNOSA { get; set; }
        public virtual DOKUMENT DOKUMENT { get; set; }
        public virtual HR_KORISNIK HR_KORISNIK { get; set; }
    }
}
