//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_KORISNIK_FILTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_KORISNIK_FILTER()
        {
            this.HR_KORISNIK_FILTER_UPOSLENIK = new HashSet<HR_KORISNIK_FILTER_UPOSLENIK>();
        }
    
        public int ID { get; set; }
        public int HR_KORISNIK_ID { get; set; }
        public string NAZIV { get; set; }
        public string AKTIVNO { get; set; }
    
        public virtual HR_KORISNIK HR_KORISNIK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_KORISNIK_FILTER_UPOSLENIK> HR_KORISNIK_FILTER_UPOSLENIK { get; set; }
    }
}
