//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_KORISNIK_HR_GRUPA
    {
        public int ID { get; set; }
        public int HR_KORISNIK_ID { get; set; }
        public int HR_GRUPA_ID { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
    
        public virtual HR_GRUPA HR_GRUPA { get; set; }
        public virtual HR_KORISNIK HR_KORISNIK { get; set; }
    }
}
