//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_KORISNIK_PRISUSTVO
    {
        public int ID { get; set; }
        public int HR_KORISNIK_ID { get; set; }
        public int VRSTA_PRISUSTVA_ODSUSTVA_ID { get; set; }
        public System.DateTime VRIJEME_OD { get; set; }
        public Nullable<System.DateTime> VRIJEME_DO { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
        public Nullable<System.DateTime> DATUM_IZMJENE { get; set; }
        public Nullable<System.DateTime> DATUM_BRISANJA { get; set; }
        public string OBRISANO { get; set; }
        public Nullable<int> REFERENT_ID { get; set; }
        public string ISHRM { get; set; }
        public string ISATTENDO { get; set; }
    
        public virtual HR_KORISNIK HR_KORISNIK { get; set; }
        public virtual HR_KORISNIK HR_KORISNIK1 { get; set; }
        public virtual VRSTA_PRISUSTVA_ODSUSTVA VRSTA_PRISUSTVA_ODSUSTVA { get; set; }
    }
}
