//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_KORISNIK_RADNO_MJESTO
    {
        public int ID { get; set; }
        public int HR_KORISNIK_ID { get; set; }
        public int RADNO_MJESTO_ID { get; set; }
        public int UGOVOR_O_RADU_ID { get; set; }
        public Nullable<int> SEDMICNO_RADNO_VRIJEME { get; set; }
        public Nullable<int> ODREDJENO_PUNO_RADNO_VRIJEME { get; set; }
        public Nullable<int> ODREDJENO_SKRACENO_RADNO_VRIJEME { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
        public Nullable<System.DateTime> DATUM_BRISANJA { get; set; }
        public string OBRISAN { get; set; }
        public string AKTIVNO { get; set; }
    
        public virtual HR_KORISNIK HR_KORISNIK { get; set; }
        public virtual RADNO_MJESTO RADNO_MJESTO { get; set; }
        public virtual UGOVOR_O_RADU UGOVOR_O_RADU { get; set; }
    }
}
