//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMDocStore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HRMDocStore()
        {
            this.HRMDocStore1 = new HashSet<HRMDocStore>();
        }
    
        public System.Guid stream_id { get; set; }
        public byte[] file_stream { get; set; }
        public string name { get; set; }
        public System.Data.Entity.Hierarchy.HierarchyId path_locator { get; set; }
        public System.Data.Entity.Hierarchy.HierarchyId parent_path_locator { get; set; }
        public string file_type { get; set; }
        public Nullable<long> cached_file_size { get; set; }
        public System.DateTimeOffset creation_time { get; set; }
        public System.DateTimeOffset last_write_time { get; set; }
        public Nullable<System.DateTimeOffset> last_access_time { get; set; }
        public bool is_directory { get; set; }
        public bool is_offline { get; set; }
        public bool is_hidden { get; set; }
        public bool is_readonly { get; set; }
        public bool is_archive { get; set; }
        public bool is_system { get; set; }
        public bool is_temporary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRMDocStore> HRMDocStore1 { get; set; }
        public virtual HRMDocStore HRMDocStore2 { get; set; }
    }
}
