//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class JUBILARNI_STAZ
    {
        public int ID { get; set; }
        public string NAZIV { get; set; }
        public int BROJ_GODINA { get; set; }
        public string AKTIVNO { get; set; }
    }
}
