//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class KANDIDAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KANDIDAT()
        {
            this.KANDIDAT_ODGOVOR = new HashSet<KANDIDAT_ODGOVOR>();
            this.REZULTAT_TESTA = new HashSet<REZULTAT_TESTA>();
        }
    
        public int ID { get; set; }
        public int HR_KORISNIK_ID { get; set; }
        public int TEST_ID { get; set; }
        public string BROJ_DOZVOLE { get; set; }
        public Nullable<int> TIP_PONAVLJANJA_TESTA_ID { get; set; }
        public Nullable<System.DateTime> DATUM_POKRETANJA_TESTA { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
    
        public virtual HR_KORISNIK HR_KORISNIK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KANDIDAT_ODGOVOR> KANDIDAT_ODGOVOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REZULTAT_TESTA> REZULTAT_TESTA { get; set; }
        public virtual TEST TEST { get; set; }
        public virtual TIP_PONAVLJANJA_TESTA TIP_PONAVLJANJA_TESTA { get; set; }
    }
}
