//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class KANDIDAT_ODGOVOR
    {
        public int ID { get; set; }
        public int KANDIDAT_ID { get; set; }
        public int TEST_ODGOVOR_ID { get; set; }
        public Nullable<int> BROJ_PONAVLJANJA_TESTA { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
    
        public virtual KANDIDAT KANDIDAT { get; set; }
        public virtual TEST_ODGOVOR TEST_ODGOVOR { get; set; }
    }
}
