//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class KANTON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KANTON()
        {
            this.LICNI_DOKUMENTI = new HashSet<LICNI_DOKUMENTI>();
            this.PREBIVALISTE_BORAVISTE = new HashSet<PREBIVALISTE_BORAVISTE>();
        }
    
        public int ID { get; set; }
        public string NAZIV { get; set; }
        public string IZDATA_OD_NAZIV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICNI_DOKUMENTI> LICNI_DOKUMENTI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PREBIVALISTE_BORAVISTE> PREBIVALISTE_BORAVISTE { get; set; }
    }
}
