//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class KONFIGURACIJA_VRSTA_PRISUSTVA
    {
        public int ID { get; set; }
        public int HR_KORISNIK_ID { get; set; }
        public int VRSTA_PRISUSTVA_ODSUSTVA_ID { get; set; }
        public string NAZIV { get; set; }
        public System.TimeSpan VRIJEME_OD { get; set; }
        public System.TimeSpan VRIJEME_DO { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
    
        public virtual HR_KORISNIK HR_KORISNIK { get; set; }
        public virtual VRSTA_PRISUSTVA_ODSUSTVA VRSTA_PRISUSTVA_ODSUSTVA { get; set; }
    }
}
