//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICNI_DOKUMENTI
    {
        public int ID { get; set; }
        public int HR_KORISNIK_ID { get; set; }
        public Nullable<int> DOKUMENT_ID { get; set; }
        public int VRSTA_LICNOG_DOKUMENTA_ID { get; set; }
        public string OZNAKA { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
        public Nullable<System.DateTime> DATUM_IZMJENE { get; set; }
        public Nullable<int> IZDATA_OD { get; set; }
        public Nullable<int> IZDATA_OD_PU_KANTON { get; set; }
        public Nullable<System.DateTime> DATUM_ISTEKA { get; set; }
    
        public virtual DOKUMENT DOKUMENT { get; set; }
        public virtual HR_KORISNIK HR_KORISNIK { get; set; }
        public virtual KANTON KANTON { get; set; }
        public virtual OPSTINA OPSTINA { get; set; }
        public virtual VRSTA_LICNOG_DOKUMENTA VRSTA_LICNOG_DOKUMENTA { get; set; }
    }
}
