//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOKACIJE_MAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOKACIJE_MAS()
        {
            this.HR_KORISNIK_LOKACIJE_MAS = new HashSet<HR_KORISNIK_LOKACIJE_MAS>();
        }
    
        public int ID { get; set; }
        public int OBJEKTI_MAS_ID { get; set; }
        public string SEKCIJA { get; set; }
        public string NAZIV { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
        public Nullable<System.DateTime> DATUM_IZMJENE { get; set; }
        public string AKTIVNO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_KORISNIK_LOKACIJE_MAS> HR_KORISNIK_LOKACIJE_MAS { get; set; }
        public virtual OBJEKTI_MAS OBJEKTI_MAS { get; set; }
    }
}
