//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MENI()
        {
            this.PRAVA_PRISTUPA = new HashSet<PRAVA_PRISTUPA>();
        }
    
        public int ID { get; set; }
        public Nullable<int> NADREDJENI_MENI_ID { get; set; }
        public string NAZIV { get; set; }
        public string URL { get; set; }
        public string AREA { get; set; }
        public string CONTROLLER { get; set; }
        public string ACTION { get; set; }
        public string IKONICA { get; set; }
        public int SORTIRANJE { get; set; }
        public string AKTIVNO { get; set; }
        public string VIDLJIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRAVA_PRISTUPA> PRAVA_PRISTUPA { get; set; }
    }
}
