//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRMEntities : DbContext
    {
        public HRMEntities()
            : base("name=HRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AttendanceEvents> AttendanceEvents { get; set; }
        public virtual DbSet<AttendoSyncStatus> AttendoSyncStatus { get; set; }
        public virtual DbSet<BRACNI_STATUS> BRACNI_STATUS { get; set; }
        public virtual DbSet<DANI_GODISNJEG_ODMORA> DANI_GODISNJEG_ODMORA { get; set; }
        public virtual DbSet<DODATNA_PRAVA_IZ_RADNOG_ODNOSA> DODATNA_PRAVA_IZ_RADNOG_ODNOSA { get; set; }
        public virtual DbSet<DODATNI_POTPISNIK> DODATNI_POTPISNIK { get; set; }
        public virtual DbSet<DODATNO_OBRAZOVANJE> DODATNO_OBRAZOVANJE { get; set; }
        public virtual DbSet<DOKUMENT> DOKUMENT { get; set; }
        public virtual DbSet<DRZAVA> DRZAVA { get; set; }
        public virtual DbSet<DRZAVLJANSTVO> DRZAVLJANSTVO { get; set; }
        public virtual DbSet<DRZAVNI_PRAZNICI> DRZAVNI_PRAZNICI { get; set; }
        public virtual DbSet<EXPORT_PRISUSTVO_POINT> EXPORT_PRISUSTVO_POINT { get; set; }
        public virtual DbSet<HR_GRUPA> HR_GRUPA { get; set; }
        public virtual DbSet<HR_KORISNIK> HR_KORISNIK { get; set; }
        public virtual DbSet<HR_KORISNIK_DODATNA_PRAVA> HR_KORISNIK_DODATNA_PRAVA { get; set; }
        public virtual DbSet<HR_KORISNIK_FILTER> HR_KORISNIK_FILTER { get; set; }
        public virtual DbSet<HR_KORISNIK_FILTER_UPOSLENIK> HR_KORISNIK_FILTER_UPOSLENIK { get; set; }
        public virtual DbSet<HR_KORISNIK_HR_GRUPA> HR_KORISNIK_HR_GRUPA { get; set; }
        public virtual DbSet<HR_KORISNIK_LOKACIJE_MAS> HR_KORISNIK_LOKACIJE_MAS { get; set; }
        public virtual DbSet<HR_KORISNIK_PRERASPODJELA_SATI> HR_KORISNIK_PRERASPODJELA_SATI { get; set; }
        public virtual DbSet<HR_KORISNIK_PRISUSTVO> HR_KORISNIK_PRISUSTVO { get; set; }
        public virtual DbSet<HR_KORISNIK_PRISUSTVO_PRAVA_PRISTUPA> HR_KORISNIK_PRISUSTVO_PRAVA_PRISTUPA { get; set; }
        public virtual DbSet<HR_KORISNIK_RADNO_MJESTO> HR_KORISNIK_RADNO_MJESTO { get; set; }
        public virtual DbSet<HR_LOG> HR_LOG { get; set; }
        public virtual DbSet<HRMDocStore> HRMDocStore { get; set; }
        public virtual DbSet<JUBILARNI_STAZ> JUBILARNI_STAZ { get; set; }
        public virtual DbSet<KANDIDAT> KANDIDAT { get; set; }
        public virtual DbSet<KANDIDAT_ODGOVOR> KANDIDAT_ODGOVOR { get; set; }
        public virtual DbSet<KANTON> KANTON { get; set; }
        public virtual DbSet<KONFIGURACIJA> KONFIGURACIJA { get; set; }
        public virtual DbSet<KONFIGURACIJA_VRSTA_PRISUSTVA> KONFIGURACIJA_VRSTA_PRISUSTVA { get; set; }
        public virtual DbSet<LICNI_DOKUMENTI> LICNI_DOKUMENTI { get; set; }
        public virtual DbSet<LOKACIJE_MAS> LOKACIJE_MAS { get; set; }
        public virtual DbSet<MENI> MENI { get; set; }
        public virtual DbSet<MIROVANJE_RADNOG_ODNOSA> MIROVANJE_RADNOG_ODNOSA { get; set; }
        public virtual DbSet<NARODNOST> NARODNOST { get; set; }
        public virtual DbSet<OBJEKTI_MAS> OBJEKTI_MAS { get; set; }
        public virtual DbSet<OBUKA> OBUKA { get; set; }
        public virtual DbSet<OPSTINA> OPSTINA { get; set; }
        public virtual DbSet<ORGANIZACIONA_JEDINICA> ORGANIZACIONA_JEDINICA { get; set; }
        public virtual DbSet<PRAVA_PRISTUPA> PRAVA_PRISTUPA { get; set; }
        public virtual DbSet<PRAVO_GODISNJI_ODMOR> PRAVO_GODISNJI_ODMOR { get; set; }
        public virtual DbSet<PREBIVALISTE_BORAVISTE> PREBIVALISTE_BORAVISTE { get; set; }
        public virtual DbSet<PRESTANAK_RADNOG_ODNOSA> PRESTANAK_RADNOG_ODNOSA { get; set; }
        public virtual DbSet<RAD_U_INOSTRANSTVU> RAD_U_INOSTRANSTVU { get; set; }
        public virtual DbSet<RADNI_STAZ> RADNI_STAZ { get; set; }
        public virtual DbSet<RADNO_ISKUSTVO> RADNO_ISKUSTVO { get; set; }
        public virtual DbSet<RADNO_MJESTO> RADNO_MJESTO { get; set; }
        public virtual DbSet<RADNO_MJESTO_SKOLSKA_SPREMA> RADNO_MJESTO_SKOLSKA_SPREMA { get; set; }
        public virtual DbSet<REZULTAT_TESTA> REZULTAT_TESTA { get; set; }
        public virtual DbSet<SIHT_LISTA_PRINT> SIHT_LISTA_PRINT { get; set; }
        public virtual DbSet<SISTEMATIZACIJA> SISTEMATIZACIJA { get; set; }
        public virtual DbSet<SKOLSKA_SPREMA> SKOLSKA_SPREMA { get; set; }
        public virtual DbSet<SPOL> SPOL { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TEST> TEST { get; set; }
        public virtual DbSet<TEST_ODGOVOR> TEST_ODGOVOR { get; set; }
        public virtual DbSet<TEST_PITANJE> TEST_PITANJE { get; set; }
        public virtual DbSet<test_preraspodjela> test_preraspodjela { get; set; }
        public virtual DbSet<TIP_OBUKE> TIP_OBUKE { get; set; }
        public virtual DbSet<TIP_ORGANIZACIONE_JEDINICE> TIP_ORGANIZACIONE_JEDINICE { get; set; }
        public virtual DbSet<TIP_PONAVLJANJA_TESTA> TIP_PONAVLJANJA_TESTA { get; set; }
        public virtual DbSet<tmp_pbroj_opstina> tmp_pbroj_opstina { get; set; }
        public virtual DbSet<UGOVOR_O_RADU> UGOVOR_O_RADU { get; set; }
        public virtual DbSet<VRSTA_ANGAZMANA> VRSTA_ANGAZMANA { get; set; }
        public virtual DbSet<VRSTA_DODATNOG_OBRAZOVANJA> VRSTA_DODATNOG_OBRAZOVANJA { get; set; }
        public virtual DbSet<VRSTA_LICNOG_DOKUMENTA> VRSTA_LICNOG_DOKUMENTA { get; set; }
        public virtual DbSet<VRSTA_PRAVA_PRISTUPA> VRSTA_PRAVA_PRISTUPA { get; set; }
        public virtual DbSet<VRSTA_PRISUSTVA_ODSUSTVA> VRSTA_PRISUSTVA_ODSUSTVA { get; set; }
        public virtual DbSet<VRSTA_RADNOG_ODNOSA> VRSTA_RADNOG_ODNOSA { get; set; }
        public virtual DbSet<VRSTA_RADNOG_STAZA> VRSTA_RADNOG_STAZA { get; set; }
        public virtual DbSet<ZAKLJUCAVANJE_EVIDENCIJE> ZAKLJUCAVANJE_EVIDENCIJE { get; set; }
    }
}
