//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJEKTI_MAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OBJEKTI_MAS()
        {
            this.LOKACIJE_MAS = new HashSet<LOKACIJE_MAS>();
        }
    
        public int ID { get; set; }
        public string NAZIV { get; set; }
        public string SKRACENI_NAZIV { get; set; }
        public string AKTIVNO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOKACIJE_MAS> LOKACIJE_MAS { get; set; }
    }
}
