//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBUKA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OBUKA()
        {
            this.TEST = new HashSet<TEST>();
        }
    
        public int ID { get; set; }
        public string OZNAKA { get; set; }
        public int TIP_OBUKE_ID { get; set; }
        public string NAZIV { get; set; }
        public Nullable<int> SORTIRANJE { get; set; }
        public string AKTIVNO { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEST> TEST { get; set; }
        public virtual TIP_OBUKE TIP_OBUKE { get; set; }
    }
}
