//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPSTINA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPSTINA()
        {
            this.HR_KORISNIK = new HashSet<HR_KORISNIK>();
            this.LICNI_DOKUMENTI = new HashSet<LICNI_DOKUMENTI>();
            this.PREBIVALISTE_BORAVISTE = new HashSet<PREBIVALISTE_BORAVISTE>();
            this.UGOVOR_O_RADU = new HashSet<UGOVOR_O_RADU>();
        }
    
        public int ID { get; set; }
        public int DRZAVA_ID { get; set; }
        public string NAZIV { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
        public string PB { get; set; }
    
        public virtual DRZAVA DRZAVA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_KORISNIK> HR_KORISNIK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICNI_DOKUMENTI> LICNI_DOKUMENTI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PREBIVALISTE_BORAVISTE> PREBIVALISTE_BORAVISTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UGOVOR_O_RADU> UGOVOR_O_RADU { get; set; }
    }
}
