//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGANIZACIONA_JEDINICA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORGANIZACIONA_JEDINICA()
        {
            this.DODATNI_POTPISNIK = new HashSet<DODATNI_POTPISNIK>();
            this.HR_KORISNIK_PRISUSTVO_PRAVA_PRISTUPA = new HashSet<HR_KORISNIK_PRISUSTVO_PRAVA_PRISTUPA>();
            this.ORGANIZACIONA_JEDINICA1 = new HashSet<ORGANIZACIONA_JEDINICA>();
            this.RADNO_MJESTO = new HashSet<RADNO_MJESTO>();
            this.SIHT_LISTA_PRINT = new HashSet<SIHT_LISTA_PRINT>();
            this.ZAKLJUCAVANJE_EVIDENCIJE = new HashSet<ZAKLJUCAVANJE_EVIDENCIJE>();
        }
    
        public int ID { get; set; }
        public Nullable<int> NADREDJENA_ORGANIZACIONA_JEDINICA_ID { get; set; }
        public int SISTEMATIZACIJA_ID { get; set; }
        public int TIP_ORGANIZACIONE_JEDINICE_ID { get; set; }
        public string KOD { get; set; }
        public string NAZIV { get; set; }
        public string OPIS_POSLOVA { get; set; }
        public string NAZIV_ZA_EXPORT_POINT { get; set; }
        public Nullable<int> POTPISNIK_RADNIH_SATI { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
        public Nullable<System.DateTime> DATUM_IZMJENE { get; set; }
        public Nullable<System.DateTime> DATUM_BRISANJA { get; set; }
        public string OBRISAN { get; set; }
        public string AKTIVNO { get; set; }
        public string NAZIV_SKRACENO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DODATNI_POTPISNIK> DODATNI_POTPISNIK { get; set; }
        public virtual HR_KORISNIK HR_KORISNIK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_KORISNIK_PRISUSTVO_PRAVA_PRISTUPA> HR_KORISNIK_PRISUSTVO_PRAVA_PRISTUPA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORGANIZACIONA_JEDINICA> ORGANIZACIONA_JEDINICA1 { get; set; }
        public virtual ORGANIZACIONA_JEDINICA ORGANIZACIONA_JEDINICA2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RADNO_MJESTO> RADNO_MJESTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIHT_LISTA_PRINT> SIHT_LISTA_PRINT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZAKLJUCAVANJE_EVIDENCIJE> ZAKLJUCAVANJE_EVIDENCIJE { get; set; }
        public virtual SISTEMATIZACIJA SISTEMATIZACIJA { get; set; }
        public virtual TIP_ORGANIZACIONE_JEDINICE TIP_ORGANIZACIONE_JEDINICE { get; set; }
    }
}
