//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRAVO_GODISNJI_ODMOR
    {
        public int ID { get; set; }
        public int HR_KORISNIK_ID { get; set; }
        public string PRAVO_NA_PUNI_ODMOR { get; set; }
        public Nullable<System.DateTime> DATUM_PRAVA_NA_PUNI_ODMOR { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
        public string OBRISAN { get; set; }
    
        public virtual HR_KORISNIK HR_KORISNIK { get; set; }
    }
}
