//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREBIVALISTE_BORAVISTE
    {
        public int ID { get; set; }
        public string TIP { get; set; }
        public int HR_KORISNIK_ID { get; set; }
        public string ADRESA { get; set; }
        public int OPSTINA_ID { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
        public Nullable<System.DateTime> DATUM_BRISANJA { get; set; }
        public string OBRISAN { get; set; }
        public string AKTIVNO { get; set; }
        public Nullable<int> KANTON_ID { get; set; }
    
        public virtual HR_KORISNIK HR_KORISNIK { get; set; }
        public virtual KANTON KANTON { get; set; }
        public virtual OPSTINA OPSTINA { get; set; }
    }
}
