//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAD_U_INOSTRANSTVU
    {
        public int ID { get; set; }
        public int HR_KORISNIK_ID { get; set; }
        public int DRZAVA_ID { get; set; }
        public string MJESTO { get; set; }
        public System.DateTime DATUM_POCETKA_RADA { get; set; }
        public Nullable<System.DateTime> DATUM_ZAVRSETKA_RADA { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
        public Nullable<System.DateTime> DATUM_IZMJENE { get; set; }
        public Nullable<System.DateTime> DATUM_BRISANJA { get; set; }
        public string OBRISAN { get; set; }
    
        public virtual DRZAVA DRZAVA { get; set; }
        public virtual HR_KORISNIK HR_KORISNIK { get; set; }
    }
}
