//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RADNO_MJESTO_SKOLSKA_SPREMA
    {
        public int ID { get; set; }
        public int RADNO_MJESTO_ID { get; set; }
        public int SKOLSKA_SPREMA_ID { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
    
        public virtual RADNO_MJESTO RADNO_MJESTO { get; set; }
        public virtual SKOLSKA_SPREMA SKOLSKA_SPREMA { get; set; }
    }
}
