//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RADNO_MJESTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RADNO_MJESTO()
        {
            this.HR_KORISNIK_RADNO_MJESTO = new HashSet<HR_KORISNIK_RADNO_MJESTO>();
            this.RADNO_MJESTO1 = new HashSet<RADNO_MJESTO>();
            this.RADNO_MJESTO_SKOLSKA_SPREMA = new HashSet<RADNO_MJESTO_SKOLSKA_SPREMA>();
        }
    
        public int ID { get; set; }
        public Nullable<int> NADREDJENO_RADNO_MJESTO_ID { get; set; }
        public int ORGANIZACIONA_JEDINICA_ID { get; set; }
        public string NAZIV { get; set; }
        public string KOD { get; set; }
        public string NAZIV_ENG { get; set; }
        public Nullable<int> BROJ_RADNIH_MJESTA { get; set; }
        public string KOEFICIJENT { get; set; }
        public string FAKULTET_SKOLA { get; set; }
        public string POSEBNI_USLOVI { get; set; }
        public string RADNO_ISKUSTVO { get; set; }
        public string POSLOVI_RADNOG_MJESTA { get; set; }
        public Nullable<int> PUNO_RADNO_VRIJEME { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
        public Nullable<System.DateTime> DATUM_IZMJENE { get; set; }
        public Nullable<System.DateTime> DATUM_BRISANJA { get; set; }
        public string OBRISAN { get; set; }
        public string UTVRDITI_RADNU_SPOSOBNOST { get; set; }
        public string AKTIVNO { get; set; }
        public string SIFRA_POINT { get; set; }
        public string OTEZANI_USLOVI_RADA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_KORISNIK_RADNO_MJESTO> HR_KORISNIK_RADNO_MJESTO { get; set; }
        public virtual ORGANIZACIONA_JEDINICA ORGANIZACIONA_JEDINICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RADNO_MJESTO> RADNO_MJESTO1 { get; set; }
        public virtual RADNO_MJESTO RADNO_MJESTO2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RADNO_MJESTO_SKOLSKA_SPREMA> RADNO_MJESTO_SKOLSKA_SPREMA { get; set; }
    }
}
