//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RADNI_STAZ
    {
        public int ID { get; set; }
        public int HR_KORISNIK_ID { get; set; }
        public int VRSTA_RADNOG_STAZA_ID { get; set; }
        public string NAZIV_FIRME { get; set; }
        public System.DateTime DATUM_OD { get; set; }
        public Nullable<System.DateTime> DATUM_DO { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
        public Nullable<System.DateTime> DATUM_IZMJENE { get; set; }
        public Nullable<System.DateTime> DATUM_BRISANJA { get; set; }
        public string OBRISAN { get; set; }
        public Nullable<int> GODINE { get; set; }
        public Nullable<int> MJESECI { get; set; }
        public Nullable<int> DANI { get; set; }
    
        public virtual HR_KORISNIK HR_KORISNIK { get; set; }
        public virtual VRSTA_RADNOG_STAZA VRSTA_RADNOG_STAZA { get; set; }
    }
}
