//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class REZULTAT_TESTA
    {
        public int ID { get; set; }
        public int TEST_ID { get; set; }
        public int KANDIDAT_ID { get; set; }
        public decimal REZULTAT { get; set; }
        public string NAPOMENA { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
    
        public virtual KANDIDAT KANDIDAT { get; set; }
        public virtual TEST TEST { get; set; }
    }
}
