//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIHT_LISTA_PRINT
    {
        public int ID { get; set; }
        public int ORGANIZACIONA_JEDINICA_ID { get; set; }
        public int MJESEC { get; set; }
        public int GODINA { get; set; }
        public string PUTANJA { get; set; }
        public string AKTIVNO { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
        public Nullable<int> POTPISNIK_ID { get; set; }
    
        public virtual ORGANIZACIONA_JEDINICA ORGANIZACIONA_JEDINICA { get; set; }
    }
}
