//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKOLSKA_SPREMA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SKOLSKA_SPREMA()
        {
            this.HR_KORISNIK = new HashSet<HR_KORISNIK>();
            this.RADNO_MJESTO_SKOLSKA_SPREMA = new HashSet<RADNO_MJESTO_SKOLSKA_SPREMA>();
        }
    
        public int ID { get; set; }
        public string NAZIV { get; set; }
        public string OZNAKA { get; set; }
        public Nullable<int> SORTIRANJE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_KORISNIK> HR_KORISNIK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RADNO_MJESTO_SKOLSKA_SPREMA> RADNO_MJESTO_SKOLSKA_SPREMA { get; set; }
    }
}
