//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class test_preraspodjela
    {
        public string prezime_ime { get; set; }
        public Nullable<decimal> broj_radnih_sati { get; set; }
        public Nullable<int> id_radnika { get; set; }
        public int id { get; set; }
    }
}
