//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEST()
        {
            this.KANDIDAT = new HashSet<KANDIDAT>();
            this.REZULTAT_TESTA = new HashSet<REZULTAT_TESTA>();
            this.TEST_PITANJE = new HashSet<TEST_PITANJE>();
        }
    
        public int ID { get; set; }
        public string NAZIV { get; set; }
        public int OBUKA_ID { get; set; }
        public int HR_KORISNIK_ID { get; set; }
        public System.DateTime DATUM_POCETKA { get; set; }
        public System.DateTime DATUM_ZAVRSETKA { get; set; }
        public Nullable<int> TRAJANJE_TESTA { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
        public string SLUCAJNI_RASPORED_PITANJA { get; set; }
        public Nullable<int> PROLAZNOST { get; set; }
        public string AKTIVNO { get; set; }
    
        public virtual HR_KORISNIK HR_KORISNIK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KANDIDAT> KANDIDAT { get; set; }
        public virtual OBUKA OBUKA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REZULTAT_TESTA> REZULTAT_TESTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEST_PITANJE> TEST_PITANJE { get; set; }
    }
}
