//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_PITANJE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEST_PITANJE()
        {
            this.TEST_ODGOVOR = new HashSet<TEST_ODGOVOR>();
        }
    
        public int ID { get; set; }
        public int TEST_ID { get; set; }
        public Nullable<int> REDNI_BROJ { get; set; }
        public string TEKST_PITANJA { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
    
        public virtual TEST TEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEST_ODGOVOR> TEST_ODGOVOR { get; set; }
    }
}
