//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_ODGOVOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEST_ODGOVOR()
        {
            this.KANDIDAT_ODGOVOR = new HashSet<KANDIDAT_ODGOVOR>();
        }
    
        public int ID { get; set; }
        public int TEST_PITANJE_ID { get; set; }
        public Nullable<int> REDNI_BROJ { get; set; }
        public string TEKST_ODGOVORA { get; set; }
        public string TACAN_ODGOVOR { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KANDIDAT_ODGOVOR> KANDIDAT_ODGOVOR { get; set; }
        public virtual TEST_PITANJE TEST_PITANJE { get; set; }
    }
}
