//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIP_ORGANIZACIONE_JEDINICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIP_ORGANIZACIONE_JEDINICE()
        {
            this.ORGANIZACIONA_JEDINICA = new HashSet<ORGANIZACIONA_JEDINICA>();
        }
    
        public int ID { get; set; }
        public string NAZIV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORGANIZACIONA_JEDINICA> ORGANIZACIONA_JEDINICA { get; set; }
    }
}
