//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UGOVOR_O_RADU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UGOVOR_O_RADU()
        {
            this.HR_KORISNIK_RADNO_MJESTO = new HashSet<HR_KORISNIK_RADNO_MJESTO>();
        }
    
        public int ID { get; set; }
        public int VRSTA_RADNOG_ODNOSA_ID { get; set; }
        public int VRSTA_ANGAZMANA_ID { get; set; }
        public Nullable<int> DOKUMENT_ID { get; set; }
        public Nullable<int> OPSTINA_ID { get; set; }
        public string BROJ_UGOVORA { get; set; }
        public string TRAJANJE_PROBNOG_RADA { get; set; }
        public string TRAJANJE_PRIPRAVNICKOG_STAZA { get; set; }
        public Nullable<System.DateTime> DATUM_UGOVORA { get; set; }
        public Nullable<System.DateTime> DATUM_POCETKA_RADA { get; set; }
        public Nullable<System.DateTime> DATUM_ZAVRSETKA_RADA { get; set; }
        public System.DateTime DATUM_KREIRANJA { get; set; }
        public Nullable<System.DateTime> DATUM_IZMJENE { get; set; }
        public string BENEFICIRANI_STAZ { get; set; }
        public Nullable<decimal> FAKTOR_UVECANJA_STAZA { get; set; }
        public string AKTIVNO { get; set; }
        public string NAPOMENA { get; set; }
        public Nullable<System.DateTime> STVARNI_POCETAK_RADA { get; set; }
    
        public virtual DOKUMENT DOKUMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_KORISNIK_RADNO_MJESTO> HR_KORISNIK_RADNO_MJESTO { get; set; }
        public virtual OPSTINA OPSTINA { get; set; }
        public virtual VRSTA_ANGAZMANA VRSTA_ANGAZMANA { get; set; }
        public virtual VRSTA_RADNOG_ODNOSA VRSTA_RADNOG_ODNOSA { get; set; }
    }
}
