//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRSTA_PRISUSTVA_ODSUSTVA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VRSTA_PRISUSTVA_ODSUSTVA()
        {
            this.HR_KORISNIK_PRISUSTVO = new HashSet<HR_KORISNIK_PRISUSTVO>();
            this.KONFIGURACIJA_VRSTA_PRISUSTVA = new HashSet<KONFIGURACIJA_VRSTA_PRISUSTVA>();
        }
    
        public int ID { get; set; }
        public string NAZIV { get; set; }
        public string SIFRA_POINT { get; set; }
        public string AKTIVNO { get; set; }
        public string SKRACENI_NAZIV { get; set; }
        public string CSS_KLASA { get; set; }
        public Nullable<int> SORTIRANJE { get; set; }
        public string EXPORT_POINT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_KORISNIK_PRISUSTVO> HR_KORISNIK_PRISUSTVO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KONFIGURACIJA_VRSTA_PRISUSTVA> KONFIGURACIJA_VRSTA_PRISUSTVA { get; set; }
    }
}
