//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRSTA_DODATNOG_OBRAZOVANJA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VRSTA_DODATNOG_OBRAZOVANJA()
        {
            this.DODATNO_OBRAZOVANJE = new HashSet<DODATNO_OBRAZOVANJE>();
        }
    
        public int ID { get; set; }
        public string NAZIV { get; set; }
        public int SORTIRANJE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DODATNO_OBRAZOVANJE> DODATNO_OBRAZOVANJE { get; set; }
    }
}
